/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package labre_trescalle;

import java.awt.HeadlessException;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author user
 */
public class TresEnCalle extends javax.swing.JFrame {

    int numTurno = 1;
    ArrayList<String> Jugador1 = new ArrayList();
    ArrayList<String> Jugador2 = new ArrayList();
    private DefaultTableModel model; //Modelo para Tabla
    private int select = -1;
    String nomJug1;
    String simboloJug1;
    String simboloJug2;
    String nomJug2;
    Integer vicJug1 = 0;
    Integer vicJug2 = 0;

    /**
     * Creates new form TresEnCalle
     */
    public TresEnCalle() {
        initComponents();
        inicio();
    }

    private void inicio() {
        jLabel_Ganador.setVisible(false);
        jLabel_Jugador.setVisible(false);
        jTb.getColumnModel().getColumn(0).setPreferredWidth(150);
        jTb.getColumnModel().getColumn(1).setPreferredWidth(35);
        jTb.getColumnModel().getColumn(2).setPreferredWidth(65);
        model = (DefaultTableModel) jTb.getModel();
        DatosJugadores();
    }

    private void DatosJugadores() throws HeadlessException {
        nomJug1 = JOptionPane.showInputDialog("Nombre Jugador 1:");
        model.setValueAt(nomJug1, 0, 0);
        String[] simbolos = {
            "X",
            "O"
        };
        MyIcon icon = new MyIcon();
        simboloJug1 = (String) JOptionPane.showInputDialog(null, "Seleccione ", "Tres en Calle", JOptionPane.DEFAULT_OPTION, icon, simbolos, simbolos[0]);
        jLabel_TurnoJugador.setText(nomJug1);
        jTextField_TurnoJugador.setText(simboloJug1);
        model.setValueAt(simboloJug1, 0, 1);
        nomJug2 = JOptionPane.showInputDialog("Nombre Jugador 2:");
        model.setValueAt(nomJug2, 1, 0);
        if (simboloJug1.equals("X")) {
            simboloJug2 = "O";
        } else {
            simboloJug2 = "X";
        }
        model.setValueAt(simboloJug2, 1, 1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        B1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        B2 = new javax.swing.JButton();
        B3 = new javax.swing.JButton();
        B4 = new javax.swing.JButton();
        B5 = new javax.swing.JButton();
        B6 = new javax.swing.JButton();
        B7 = new javax.swing.JButton();
        B8 = new javax.swing.JButton();
        B9 = new javax.swing.JButton();
        jLabel_Ganador = new javax.swing.JLabel();
        jLabel_Jugador = new javax.swing.JLabel();
        jLabel_Turno = new javax.swing.JLabel();
        jTextField_TurnoJugador = new javax.swing.JTextField();
        jButton_NuevoJuego = new javax.swing.JButton();
        jLabel_TurnoJugador = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTb = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        B1.setFont(new java.awt.Font("Lucida Fax", 1, 36)); // NOI18N
        B1.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 153, 153)));
        B1.setBorderPainted(false);
        B1.setName("B1"); // NOI18N
        B1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B1MouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel1.setText("TRES EN CALLE");

        B2.setFont(new java.awt.Font("Lucida Fax", 1, 36)); // NOI18N
        B2.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 153, 153)));
        B2.setBorderPainted(false);
        B2.setName("B2"); // NOI18N
        B2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B2MouseClicked(evt);
            }
        });

        B3.setFont(new java.awt.Font("Lucida Fax", 1, 36)); // NOI18N
        B3.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 153, 153)));
        B3.setBorderPainted(false);
        B3.setName("B3"); // NOI18N
        B3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B3MouseClicked(evt);
            }
        });

        B4.setFont(new java.awt.Font("Lucida Fax", 1, 36)); // NOI18N
        B4.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 153, 153)));
        B4.setBorderPainted(false);
        B4.setName("B4"); // NOI18N
        B4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B4MouseClicked(evt);
            }
        });

        B5.setFont(new java.awt.Font("Lucida Fax", 1, 36)); // NOI18N
        B5.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 153, 153)));
        B5.setBorderPainted(false);
        B5.setName("B5"); // NOI18N
        B5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B5MouseClicked(evt);
            }
        });

        B6.setFont(new java.awt.Font("Lucida Fax", 1, 36)); // NOI18N
        B6.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 153, 153)));
        B6.setBorderPainted(false);
        B6.setName("B6"); // NOI18N
        B6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B6MouseClicked(evt);
            }
        });

        B7.setFont(new java.awt.Font("Lucida Fax", 1, 36)); // NOI18N
        B7.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 153, 153)));
        B7.setBorderPainted(false);
        B7.setName("B7"); // NOI18N
        B7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B7MouseClicked(evt);
            }
        });

        B8.setFont(new java.awt.Font("Lucida Fax", 1, 36)); // NOI18N
        B8.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 153, 153)));
        B8.setBorderPainted(false);
        B8.setName("B8"); // NOI18N
        B8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B8MouseClicked(evt);
            }
        });

        B9.setFont(new java.awt.Font("Lucida Fax", 1, 36)); // NOI18N
        B9.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 153, 153)));
        B9.setBorderPainted(false);
        B9.setName("B9"); // NOI18N
        B9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B9MouseClicked(evt);
            }
        });

        jLabel_Ganador.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel_Ganador.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Ganador.setMaximumSize(new java.awt.Dimension(200, 21));
        jLabel_Ganador.setMinimumSize(new java.awt.Dimension(110, 21));

        jLabel_Jugador.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N

        jLabel_Turno.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel_Turno.setText("Turno: ");

        jTextField_TurnoJugador.setEditable(false);
        jTextField_TurnoJugador.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N

        jButton_NuevoJuego.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jButton_NuevoJuego.setText("Nuevo Juego");
        jButton_NuevoJuego.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_NuevoJuegoActionPerformed(evt);
            }
        });

        jLabel_TurnoJugador.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N

        jTb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Jugador", "X/O", "Victoria"
            }
        ));
        jScrollPane1.setViewportView(jTb);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel_Ganador, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(70, 70, 70)
                                .addComponent(jLabel_TurnoJugador, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(jLabel_Jugador, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel_Turno, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jTextField_TurnoJugador, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(B1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(B2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addComponent(B3, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(B4, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(B5, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addComponent(B6, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(B7, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(B8, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addComponent(B9, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jButton_NuevoJuego, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel_Ganador, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_TurnoJugador, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_Jugador, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel_Turno))
                    .addComponent(jTextField_TurnoJugador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(B1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B3, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(B4, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B5, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B6, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(B7, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B8, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B9, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addComponent(jButton_NuevoJuego)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void B1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B1MouseClicked
        asignarTurno(B1);
    }//GEN-LAST:event_B1MouseClicked

    private void B2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B2MouseClicked
        asignarTurno(B2);
    }//GEN-LAST:event_B2MouseClicked

    private void B3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B3MouseClicked
        asignarTurno(B3);
    }//GEN-LAST:event_B3MouseClicked

    private void B4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B4MouseClicked
        asignarTurno(B4);
    }//GEN-LAST:event_B4MouseClicked

    private void B5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B5MouseClicked
        asignarTurno(B5);
    }//GEN-LAST:event_B5MouseClicked

    private void B6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B6MouseClicked
        asignarTurno(B6);
    }//GEN-LAST:event_B6MouseClicked

    private void B7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B7MouseClicked
        asignarTurno(B7);
    }//GEN-LAST:event_B7MouseClicked

    private void B8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B8MouseClicked
        asignarTurno(B8);
    }//GEN-LAST:event_B8MouseClicked

    private void B9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B9MouseClicked
        asignarTurno(B9);
    }//GEN-LAST:event_B9MouseClicked

    private void jButton_NuevoJuegoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_NuevoJuegoActionPerformed
        // TODO add your handling code here:
        limpiarTodo();
    }//GEN-LAST:event_jButton_NuevoJuegoActionPerformed

    private void ningunoGana() {
        if (numTurno == 10) {
            jLabel_Ganador.setText("NINGUNO GANA");
            jLabel_Ganador.setVisible(true);
            jLabel_Turno.setVisible(false);
            jLabel_TurnoJugador.setVisible(false);
            jTextField_TurnoJugador.setVisible(false);
        }
    }

    private void imprimirTurno() {
        if (numTurno % 2 == 0) {
            jLabel_TurnoJugador.setText(nomJug2);
            jTextField_TurnoJugador.setText(simboloJug2);
        } else {
            jLabel_TurnoJugador.setText(nomJug1);
            jTextField_TurnoJugador.setText(simboloJug1);
        }
    }

    private void asignarTurno(Object BotonPres) {
        JButton Boton = (JButton) BotonPres;
        if (numTurno % 2 == 0 && Boton.isEnabled()) {
            Boton.setText(simboloJug2);
            numTurno++;
            Jugador2.add(Boton.getName());
        } else if (Boton.isEnabled()) {
            Boton.setText(simboloJug1);
            numTurno++;
            Jugador1.add(Boton.getName());
        }
        ningunoGana();
        imprimirTurno();
        Boton.setEnabled(false);
        imprimirGanador();
    }

    private void imprimirGanador() {
        if (Ganador(Jugador1, simboloJug1)) {
            jLabel_Ganador.setText("¡GANADOR!");
            jLabel_Ganador.setVisible(true);
            jLabel_Jugador.setText(nomJug1);
            jLabel_Jugador.setVisible(true);
            jLabel_Turno.setVisible(false);
            jLabel_TurnoJugador.setVisible(false);
            jTextField_TurnoJugador.setVisible(false);
            vicJug1++;
        } else if (Ganador(Jugador2, simboloJug2)) {
            jLabel_Ganador.setText("¡GANADOR!");
            jLabel_Ganador.setVisible(true);
            jLabel_Jugador.setText(nomJug2);
            jLabel_Jugador.setVisible(true);
            jLabel_Turno.setVisible(false);
            jLabel_TurnoJugador.setVisible(false);
            jTextField_TurnoJugador.setVisible(false);
            vicJug2++;
        }
        model.setValueAt(vicJug1, 0, 2);
        model.setValueAt(vicJug2, 1, 2);
    }

    private void limpiarTodo() {
        Jugador1.clear();
        Jugador2.clear();
        numTurno = 1;
        int lim;
        ArrayList Botones = new ArrayList();
        Botones.add(B1);
        Botones.add(B2);
        Botones.add(B3);
        Botones.add(B4);
        Botones.add(B5);
        Botones.add(B6);
        Botones.add(B7);
        Botones.add(B8);
        Botones.add(B9);
        lim = Botones.size();
        for (int i = 0; i < lim; i++) {
            ((JButton) (Botones.get(i))).setText("");
            ((JButton) (Botones.get(i))).setEnabled(true);
            ((JButton) (Botones.get(i))).setBorderPainted(false);
        }
        jLabel_Ganador.setVisible(false);
        jLabel_Jugador.setVisible(false);
        jLabel_TurnoJugador.setText(nomJug1);
        jTextField_TurnoJugador.setText(simboloJug1);
        jLabel_TurnoJugador.setVisible(true);
        jTextField_TurnoJugador.setVisible(true);
        jLabel_Turno.setVisible(true);
    }

    private void imprimirBotonesGanador(ArrayList Jugador) {
        for (int i = 0; i < Jugador.size(); i++) {
            switch ((Integer) Jugador.get(i)) {
                case 1:
                    B1.setBorderPainted(true);
                    break;
                case 2:
                    B2.setBorderPainted(true);
                    break;
                case 3:
                    B3.setBorderPainted(true);
                    break;
                case 4:
                    B4.setBorderPainted(true);
                    break;
                case 5:
                    B5.setBorderPainted(true);
                    break;
                case 6:
                    B6.setBorderPainted(true);
                    break;
                case 7:
                    B7.setBorderPainted(true);
                    break;
                case 8:
                    B8.setBorderPainted(true);
                    break;
                case 9:
                    B9.setBorderPainted(true);
            }
        }
        B1.setEnabled(false);
        B2.setEnabled(false);
        B3.setEnabled(false);
        B4.setEnabled(false);
        B5.setEnabled(false);
        B6.setEnabled(false);
        B7.setEnabled(false);
        B8.setEnabled(false);
        B9.setEnabled(false);
    }

    private boolean Ganador(ArrayList Jugador, String Tipo_X_O) {
        ArrayList<Integer> Ganador = new ArrayList();
        boolean gana = false;
        String Bot1, Bot2, Bot3, Bot4, Bot5, Bot6, Bot7, Bot8, Bot9;
        Bot1 = Bot2 = Bot3 = Bot4 = Bot5 = Bot6 = Bot7 = Bot8 = Bot9 = null;
        for (int i = 0; i < Jugador.size(); i++) {
            if (Jugador.get(i) == "B1") {
                Bot1 = Tipo_X_O;
            } else if (Jugador.get(i) == "B2") {
                Bot2 = Tipo_X_O;
            } else if (Jugador.get(i) == "B3") {
                Bot3 = Tipo_X_O;
            } else if (Jugador.get(i) == "B4") {
                Bot4 = Tipo_X_O;
            } else if (Jugador.get(i) == "B5") {
                Bot5 = Tipo_X_O;
            } else if (Jugador.get(i) == "B6") {
                Bot6 = Tipo_X_O;
            } else if (Jugador.get(i) == "B7") {
                Bot7 = Tipo_X_O;
            } else if (Jugador.get(i) == "B8") {
                Bot8 = Tipo_X_O;
            } else if (Jugador.get(i) == "B9") {
                Bot9 = Tipo_X_O;
            }
        }
        if (Bot1 == Tipo_X_O && Bot2 == Tipo_X_O && Bot3 == Tipo_X_O) {
            Ganador.add(1);
            Ganador.add(2);
            Ganador.add(3);
            gana = true;
        } else if (Bot4 == Tipo_X_O && Bot5 == Tipo_X_O && Bot6 == Tipo_X_O) {
            Ganador.add(4);
            Ganador.add(5);
            Ganador.add(6);
            gana = true;
        } else if (Bot7 == Tipo_X_O && Bot8 == Tipo_X_O && Bot9 == Tipo_X_O) {
            Ganador.add(7);
            Ganador.add(8);
            Ganador.add(9);
            gana = true;
        } else if (Bot1 == Tipo_X_O && Bot4 == Tipo_X_O && Bot7 == Tipo_X_O) {
            Ganador.add(1);
            Ganador.add(4);
            Ganador.add(7);
            gana = true;
        } else if (Bot2 == Tipo_X_O && Bot5 == Tipo_X_O && Bot8 == Tipo_X_O) {
            Ganador.add(2);
            Ganador.add(5);
            Ganador.add(8);
            gana = true;
        } else if (Bot3 == Tipo_X_O && Bot6 == Tipo_X_O && Bot9 == Tipo_X_O) {
            Ganador.add(3);
            Ganador.add(6);
            Ganador.add(9);
            gana = true;
        } else if (Bot3 == Tipo_X_O && Bot5 == Tipo_X_O && Bot7 == Tipo_X_O) {
            Ganador.add(3);
            Ganador.add(5);
            gana = true;
            Ganador.add(7);
        } else if (Bot1 == Tipo_X_O && Bot5 == Tipo_X_O && Bot9 == Tipo_X_O) {
            Ganador.add(1);
            Ganador.add(5);
            Ganador.add(9);
            gana = true;
        }
        if (gana) {
            imprimirBotonesGanador(Ganador);
        }
        return gana;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TresEnCalle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TresEnCalle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TresEnCalle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TresEnCalle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TresEnCalle().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B1;
    private javax.swing.JButton B2;
    private javax.swing.JButton B3;
    private javax.swing.JButton B4;
    private javax.swing.JButton B5;
    private javax.swing.JButton B6;
    private javax.swing.JButton B7;
    private javax.swing.JButton B8;
    private javax.swing.JButton B9;
    private javax.swing.JButton jButton_NuevoJuego;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel_Ganador;
    private javax.swing.JLabel jLabel_Jugador;
    private javax.swing.JLabel jLabel_Turno;
    private javax.swing.JLabel jLabel_TurnoJugador;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTb;
    private javax.swing.JTextField jTextField_TurnoJugador;
    // End of variables declaration//GEN-END:variables
}
